(function(a){a.cookieCuttr=function(b){var e={cookieCutter:!1,cookieCutterDeclineOnly:!1,cookieAnalytics:!1,cookieDeclineButton:!1,cookieAcceptButton:!0,cookieResetButton:!1,cookieOverlayEnabled:!1,cookiePolicyLink:"/privacy-policy/",cookieMessage:'<div>Spletno mesto uporablja pi\u0161kotke za zagotavljanje spletne storitve, analizo uporabe{{cookieMsg}} funkcionalnosti,  ki jih brez pi\u0161kotkov ne bi mogli nuditi. Z nadaljnjo uporabo spletnega mesta sogla\u0161ate s pi\u0161kotki. Nastavitve pi\u0161kotkov si lahko uredite <a href="{{cookiePolicyLink}}" title="Ve\u010d" class="readMore" target="_blank">tukaj</a><br><br>Obdelava podatkov poteka v skladu z zakonom in Splo\u0161no uredbo o varovanju osebnih podatkov. Ve\u010d o <a href="https://siol.net/pogoji-uporabe" title="Ve\u010d" class="readMore" target="_blank">Pogojih uporabe spletnega mesta</a>.</div>',
cookieAnalyticsMessage:"We use cookies, just to track visits to our website, we store no personal details.",cookieErrorMessage:"We're sorry, this feature places cookies in your browser and has been disabled. <br>To continue using this functionality, please",cookieWhatAreTheyLink:"http://www.allaboutcookies.org/",cookieDisable:"",cookieExpires:365,cookieAcceptButtonText:" V redu ",cookieDeclineButtonText:"DECLINE COOKIES",cookieResetButtonText:"RESET COOKIES FOR THIS WEBSITE",cookieWhatAreLinkText:"What are cookies?",
cookieNotificationLocationBottom:!0,cookiePolicyPage:!1,cookiePolicyPageMessage:"Please read the information below and then choose from the following options",cookieDiscreetLink:!1,cookieDiscreetReset:!1,cookieDiscreetLinkText:"Cookies?",cookieDiscreetPosition:"topleft",cookieNoMessage:!1,cookieDomain:"",cookieCloseButton:!0,cookieAcceptButtonColor:"7DAF3B",cookieNamePostFix:"",isGeneralType:!1,cookieGeneralMsg:", oglasnih sistemov in",cookieAdMsg:" in"},b=a.extend(e,b),k="",k=b.isGeneralType?e.cookieMessage.replace("{{cookieMsg}}",
e.cookieGeneralMsg):e.cookieMessage.replace("{{cookieMsg}}",e.cookieAdMsg);e.cookieMessage='We use cookies on this website, you can <a href="'+e.cookiePolicyLink+'" title="read about our cookies">read about them here</a>. To use the website as intended please...';var e=b.cookiePolicyLink,l=b.cookieCutter,h=b.cookieCutterDeclineOnly,i=b.cookieAnalytics,d=b.cookieDeclineButton,c=b.cookieAcceptButton,j=b.cookieResetButton,f=b.cookieOverlayEnabled,k=k.replace("{{cookiePolicyLink}}",b.cookiePolicyLink),
m=b.cookieAnalyticsMessage,n=b.cookieErrorMessage,x=b.cookieDisable,B=b.cookieWhatAreTheyLink,p=b.cookieExpires,q=b.cookieAcceptButtonText,y=b.cookieDeclineButtonText,u=b.cookieResetButtonText,C=b.cookieWhatAreLinkText,z=b.cookieNotificationLocationBottom,r=b.cookiePolicyPage,D=b.cookiePolicyPageMessage,s=b.cookieDiscreetLink,E=b.cookieDiscreetReset,A=b.cookieDiscreetLinkText,o=b.cookieDiscreetPosition,F=b.cookieNoMessage,v=b.cookieCloseButton,G=b.cookieAcceptButtonColor,g=b.cookieNamePostFix;a.getCookieNamePostFix=
function(){return g};a.getCookieExpiration=function(){return p};var w="cc_cookie_accept"==a.cookie("cc_cookie_accept_"+g);a.cookieAccepted=function(){return w};var t="cc_cookie_decline"==a.cookie("cc_cookie_decline_"+g);a.cookieDeclined=function(){return t};c=c?' <a href="#accept" class="cc-cookie-accept" style="background:#'+G+';">'+q+"</a> ":"";d=d?' <a href="#decline" class="cc-cookie-decline">'+y+"</a> ":"";v=v?' <a href="#close" class="cc-cookie-close">X</a> ':"";f=f?"cc-overlay":"";if(w||t)if(j&&
E){if(a('<div class="cc-cookies cc-discreet"><a class="cc-cookie-reset" href="#" title="'+u+'">'+u+"</a></div>").prependTo("body"),"topleft"==o&&(a("div.cc-cookies").css("top","0"),a("div.cc-cookies").css("left","0")),"topright"==o&&(a("div.cc-cookies").css("top","0"),a("div.cc-cookies").css("right","0")),"bottomleft"==o&&(a("div.cc-cookies").css("bottom","0"),a("div.cc-cookies").css("left","0")),"bottomright"==o)a("div.cc-cookies").css("bottom","0"),a("div.cc-cookies").css("right","0")}else j?a("body").prependTo('<div class="cc-cookies"><a href="#" class="cc-cookie-reset">'+
u+"</a></div>"):j="";else{if(!F||r)if(s&&!r){if(a('<div class="cc-cookies cc-discreet"><a href="'+e+'" title="'+A+'">'+A+"</a></div>").prependTo("body"),"topleft"==o&&(a("div.cc-cookies").css("top","0"),a("div.cc-cookies").css("left","0")),"topright"==o&&(a("div.cc-cookies").css("top","0"),a("div.cc-cookies").css("right","0")),"bottomleft"==o&&(a("div.cc-cookies").css("bottom","0"),a("div.cc-cookies").css("left","0")),"bottomright"==o)a("div.cc-cookies").css("bottom","0"),a("div.cc-cookies").css("right",
"0")}else i&&a('<div class="cc-cookies '+f+'">'+m+c+d+'<a href="'+B+'" title="Visit All about cookies (External link)">'+C+"</a></div>").prependTo("body");r?a('<div class="cc-cookies '+f+'">'+D+'  <a href="#accept" class="cc-cookie-accept">'+q+'</a>  <a href="#decline" class="cc-cookie-decline">'+y+"</a> </div>").prependTo("body"):!i&&!s&&a('<div class="cc-cookies '+f+'">'+k+c+d+v+"</div>").prependTo("body")}l&&!h&&(t||!w)&&a(x).html('<div class="cc-cookies-error">'+n+' <a href="#accept" class="cc-cookie-accept">'+
q+"</a> </div>");l&&h&&t&&a(x).html('<div class="cc-cookies-error">'+n+' <a href="#accept" class="cc-cookie-accept">'+q+"</a> </div>");z&&!s&&(a("div.cc-cookies").css("top","auto"),a("div.cc-cookies").css("bottom","0"));z&&s&&r&&(a("div.cc-cookies").css("top","auto"),a("div.cc-cookies").css("bottom","0"));a(".cc-cookie-accept, .cc-cookie-decline, .cc-cookie-close").click(function(m){m.preventDefault();if(a(this).is("[href$=#decline]")){a.cookie("cc_cookie_accept_"+g,null,{path:"/"});a.cookie("cc_cookie_decline_"+
g,"cc_cookie_decline",{expires:p,path:"/"});if(b.cookieDomain){a.cookie("__utma",null,{domain:"."+b.cookieDomain,path:"/"});a.cookie("__utmb",null,{domain:"."+b.cookieDomain,path:"/"});a.cookie("__utmc",null,{domain:"."+b.cookieDomain,path:"/"});a.cookie("__utmz",null,{domain:"."+b.cookieDomain,path:"/"})}}else{a.cookie("cc_cookie_decline_"+g,null,{path:"/"});a.cookie("cc_cookie_accept_"+g,"cc_cookie_accept",{expires:p,path:"/"})}a(".cc-cookies").slideUp(function(){typeof isCCSettingSite==="undefined"&&
location.reload()})});a("a.cc-cookie-reset").click(function(m){m.preventDefault();a.cookie("cc_cookie_accept_"+g,null,{path:"/"});a.cookie("cc_cookie_decline_"+g,null,{path:"/"});a(".cc-cookies").fadeOut(function(){location.reload()})});a(".cc-cookies-error a.cc-cookie-accept").click(function(m){m.preventDefault();a.cookie("cc_cookie_accept_"+g,"cc_cookie_accept",{expires:p,path:"/"});a.cookie("cc_cookie_decline_"+g,null,{path:"/"});location.reload()});a(document).bind("keyup",function(a){if(a.keyCode===
13&&jQuery(".cc-cookies").length>0){a.preventDefault();jQuery(".cc-cookie-accept").click()}});a(document).ready(function(){jQuery(".cc-cookies").length>0&&jQuery("body a").click(function(){if(!jQuery(this).hasClass("readMore")){a.cookie("cc_cookie_decline_"+g,null,{path:"/"});a.cookie("cc_cookie_accept_"+g,"cc_cookie_accept",{expires:p,path:"/"})}})})}})(jQuery);
(function(a){"function"===typeof define&&define.amd?define(["jquery"],a):a(jQuery)})(function(a){function b(a){return a}function e(a){try{return decodeURIComponent(a.replace(l," "))}catch(b){return a}}function k(a){0===a.indexOf('"')&&(a=a.slice(1,-1).replace(/\\"/g,'"').replace(/\\\\/g,"\\"));try{return h.json?JSON.parse(a):a}catch(b){}}var l=/\+/g,h=a.cookie=function(i,d,c){if(void 0!==d){c=a.extend({},h.defaults,c);if("number"===typeof c.expires){var j=c.expires,f=c.expires=new Date;f.setDate(f.getDate()+
j)}d=h.json?JSON.stringify(d):""+d;return document.cookie=[h.raw?i:encodeURIComponent(i),"=",h.raw?d:encodeURIComponent(d),c.expires?"; expires="+c.expires.toUTCString():"",c.path?"; path="+c.path:"",c.domain?"; domain="+c.domain:"",c.secure?"; secure":""].join("")}for(var d=h.raw?b:e,c=document.cookie.split("; "),j=i?void 0:{},f=0,m=c.length;f<m;f++){var n=c[f].split("="),l=d(n.shift()),n=d(n.join("="));if(i&&i===l){j=k(n);break}i||(j[l]=k(n))}return j};h.defaults={};a.removeCookie=function(b,d){return void 0!==
a.cookie(b)?(a.cookie(b,"",a.extend({},d,{expires:-1})),!0):!1}});
function cc_fn(a){var a=$.extend({cookieNamePostFix:"",cookieExpires:365,initAllowAdvertising:!0,initAllowAnalytics:!0,initAllowSocial:!0,showPopup:!1,popupOnDeniedAdvertising:!0,popupOnDeniedAnalytics:!1,popupOnDeniedSocial:!1,popupSettingPageURL:"",popupText:'Spletno mesto za dostop do brezpla\u010dnih vsebin potrebuje soglasje za uporabo pi\u0161kotkov za napredne oglasne sisteme in u\u010dinkovitej\u0161e ogla\u0161evanje.<br /><br /><a href="#" title="\u017delim vsebino" class="cc-btn-allin" onclick="cca.initCookieAction(true);return false;">\u017delim vsebino</a><br /><br /><a href="{{popupSettingPageURL}}" title="Ve\u010d" class="readMore" target="_blank">Podrobne nastavitve</a>'},a),
b=a.cookieNamePostFix,e=a.cookieExpires,k=a.initAllowAdvertising,l=a.initAllowAnalytics,h=a.initAllowSocial,i=a.showPopup,d=a.popupOnDeniedAdvertising,c=a.popupOnDeniedAnalytics,j=a.popupOnDeniedSocial,f=a.popupText.replace("{{popupSettingPageURL}}",a.popupSettingPageURL);this.cookieGeneralAccepted=function(){return"cc_cookie_accept"===$.cookie("cc_cookie_accept_"+b)};this.cookieAllowSocial=function(a){if(!0===a||!1===a)return $.cookie("cc_cookie_social_"+b,a,{expires:e,path:"/"}),a;a=$.cookie("cc_cookie_social_"+
b);return void 0===a?null:"true"===a};this.cookieAllowAdvertising=function(a){if(!0===a||!1===a)return $.cookie("cc_cookie_advertising_"+b,a,{expires:e,path:"/"}),a;a=$.cookie("cc_cookie_advertising_"+b);return void 0===a?null:"true"===a};this.cookieAllowAnalytics=function(a){if(!0===a||!1===a)return $.cookie("cc_cookie_analytics_"+b,a,{expires:e,path:"/"}),a;a=$.cookie("cc_cookie_analytics_"+b);return void 0===a?null:"true"===a};this.reInit=function(){this.cookieAllowAdvertising()&&$("script[type*=plain].cc-adv").each(function(){$(this).attr("type",
"text/javascript");$(this).removeClass("cc-adv");var a=$.trim($(this).attr("src"));void 0!==a&&""!==a?($(this).attr("src",""),$(this).remove(),document.writeln('<script type="text/javascript" src="'+a+'"><\/script>')):(a=$(this).html(),$(this).remove(),document.writeln('<script type="text/javascript">'+a+"<\/script>"))});this.cookieAllowSocial()&&$("script[type*=plain].cc-socl").each(function(){$(this).attr("type","text/javascript");var a=$(this).attr("src");void 0!==a?($(this).attr("src",""),$(this).attr("src",
a)):(a=$(this).html(),$(this).remove(),document.writeln('<script type="text/javascript">'+a+"<\/script>"))});this.cookieAllowAnalytics()&&$("script[type*=plain].cc-analytics").each(function(){$(this).attr("type","text/javascript");var a=$(this).attr("src");void 0!==a?($(this).attr("src",""),$(this).attr("src",a)):(a=$(this).html(),$(this).remove(),document.writeln('<script type="text/javascript">'+a+"<\/script>"))})};this.initCookieAction=function(a){if(this.cookieGeneralAccepted()&&(void 0===$.cookie("cc_cookie_action_"+
b)||!0===a))$.cookie("cc_cookie_action_"+b,"1",{expires:e,path:"/"}),this.cookieAllowAdvertising(k),this.cookieAllowAnalytics(l),this.cookieAllowSocial(h),!0===a&&location.reload()};this.initCookieAction();!0===i&&(a=!1,!0===d&&!1===this.cookieAllowAdvertising()&&(a=!0),!0===c&&!1===this.cookieAllowAnalytics()&&(a=!0),!0===j&&!1===this.cookieAllowSocial()&&(a=!0),"1"!==$.cookie("cc_cookie_action_"+b)&&(a=!1),a&&$(document).ready(function(){var a=void 0;try{a=isCCSettingSite}catch(b){a=void 0}!0!==
a&&$("body").append('<div class="cc_notice_ovr">&nbsp;</div><div class="cc_notice_setting_wrapper"><div class="cc_notice_setting cc-cookies"><div>'+f+"</div></div></div>")}))};
